file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/priya/.gitconfig	user.email=rajkm9111@gmail.com
file:C:/Users/priya/.gitconfig	user.name=CODER-Rxj11
file:C:/Users/priya/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/priya/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/priya/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/priya/.gitconfig	filter.lfs.required=true
file:C:/Users/priya/.gitconfig	code.editor=code --wait
file:C:/Users/priya/.gitconfig	core.autovrlf=input
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/CODER-Rxj11/BQC.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
